### ISSUE TITLE
"NOASSERTION" license on License Rankings

### ISSUE THREAD

**Issue by verhovsky** [github/innovationgraph#2]
https://innovationgraph.github.com/global-metrics/licenses

I think this should be removed or changed to something more obvious like "Unknown". Because it's capitalized I thought "NOASSERTION" might be something about not asserting some copyrights or something and googling "noassertion license" didn't produce immediately obvious results.

**Comment by mlinksva** [comment]
You're right, it's a [term](https://spdx.github.io/spdx-spec/v2.3/package-information/#713-concluded-license-field) that only people very involved in open source licensing details would recognize, apologies for missing that (because I have been one of those people at times).

We'll change the display in the chart or at least add on-page documentation shortly. 💭

**Comment by mlinksva** [comment]
Added an explanation to the datasheet. @khxu will make a corresponding update to the website to close this out. Thanks again for reporting @verhovsky!

**Comment by mlinksva** [comment]
Fixed with nthe latest quarterly data release https://github.blog/2024-04-09-explore-the-seasons-of-software-development-with-four-full-years-of-data/#noassertion-changed-to-other-in-the-licenses-bump-charts
